// Acciones sincronas
export const CAMBIAR_RUTA = 'CAMBIAR_RUTA';
export const CAMBIAR_ESTA_LOGUEADO = 'CAMBIAR_ESTA_LOGUEADO';
export const CAMBIAR_ES_ADMIN = 'CAMBIAR_ES_ADMIN';


// Acciones asincronas
export const FETCH_USUARIO_PENDIENTE = 'FETCH_USUARIO_PENDIENTE'
export const FETCH_USUARIO_EXITOSO = 'FETCH_USUARIO_EXITOSO'
export const FETCH_USUARIO_FALLIDO = 'FETCH_USUARIO_FALLIDO'


